'use strict';
const $=id=>document.getElementById(id);
const BASE=document.documentElement.dataset.apiBase||'';
const SHARED=document.documentElement.dataset.shared==='true';
const NEURAL=new Set(['fly','rewired','untrained','disconnected','silenced']);
const names={fly:'真实果蝇网络',rewired:'随机重连＋已训练读出',direct:'直接状态＋已训练读出',untrained:'果蝇网络＋随机读出',disconnected:'断开全部连接',silenced:'关闭感觉输入',random:'随机动作（未训练）',rule:'规则跟球',manual:'左侧手动'};
const notes={fly:'真实连接图，动作读出事先用示范训练。右侧由你控制，左侧只接收神经活动的读出；当前不继续学习。',rewired:'人工打乱连接来源的网络，读出器用与果蝇组相同的示范重新训练。它不是随机按键，也不是实测果蝇连接。',direct:'直接输入球位置、球拍位置和速度，用同一份示范训练线性动作模型；不经过神经网络。',untrained:'保留真实果蝇连接，换成固定随机读出器；这一读出器没有训练。',disconnected:'感觉输入保留，全部神经元间连接关闭，仍使用果蝇组原先训练好的读出器。',silenced:'保留连接和读出器，外部感觉输入归零。',random:'随机选择向上、向下或不动；完全没有训练。这与上面的随机重连网络是不同的对照。',rule:'直接根据球与球拍的高度差跟球；这条明确规则也用于生成训练示范。'};
const eventNames={hit:'左侧接住了',miss:'你得分 · 左侧漏球',human_hit:'你接住了',human_miss:'你漏球了 · 再发一球',serve:'你发球了'};
let current=null,meta=null,stopped=false,failures=0,trail=[],noticeTimer=null;
let clientY=.5,clientAim=-20,pendingMove=null,commands=[],controlBusy=false,benchKey='';
let moveBusy=false,moveTimer=null,lastMoveSent=-Infinity,viewGame=null,viewAt=0;
let rttSamples=[],networkRtt=0,uiDue=0,fps=0,frameCount=0,frameAt=performance.now(),animation=null,eventsKey='';
let backdrop=null;
function notice(text){clearTimeout(noticeTimer);$('notice').textContent=text;$('notice').style.display='block';noticeTimer=setTimeout(()=>$('notice').style.display='none',4500);}
async function api(path,body){const abort=new AbortController(),start=performance.now();const timer=setTimeout(()=>abort.abort(),8000);try{const r=await fetch(BASE+path,{cache:'no-store',signal:abort.signal,...(body!==undefined?{method:'POST',headers:{'Content-Type':'application/json','X-FlyWire-Control':'1'},body:JSON.stringify(body)}:{})});if(!r.ok){const err=await r.json().catch(()=>({error:r.status}));throw new Error(err.error||r.status);}const data=await r.json(),elapsed=performance.now()-start;if(['/api/state','/api/input','/api/control'].includes(path)){rttSamples.push(elapsed);rttSamples=rttSamples.slice(-12);networkRtt=[...rttSamples].sort((a,b)=>a-b)[Math.floor(rttSamples.length/2)];}if(data.game)data._rtt=elapsed;return data;}finally{clearTimeout(timer);}}
function updatePlayerLabels(){$('player-height').value=Math.round(clientY*100);$('aim').value=clientAim;$('aim-label').textContent=clientAim===0?'水平':`${clientAim<0?'向上':'向下'} ${Math.abs(clientAim)}°`;}
function accept(next,sync=false){if(next.version!==2)throw new Error('实验台正在升级，请稍后刷新。');const now=performance.now();const discontinuity=!current||next.game.seed!==current.game.seed||next.mode!==current.mode||next.game.waiting_serve!==current.game.waiting_serve||next.game.time<current.game.time;if(discontinuity)trail=[];const advanced=!current||next.game.time!==current.game.time;if(discontinuity||advanced||next.paused||next.game.waiting_serve){viewGame=next.game;viewAt=now-Math.min(200,(next._rtt||0)/2+(next.server_age_ms||0));if(advanced&&!discontinuity){trail.push(next.game.ball);trail=trail.slice(-10);}}current=next;if(sync){clientY=next.game.right_target;clientAim=next.game.aim;updatePlayerLabels();}if(sync||discontinuity||now>=uiDue){render();uiDue=now+100;}}
function control(body){commands.push(body);pump();}
function movePlayer(y,aim){const oldY=clientY,oldAim=clientAim;if(y!==undefined)clientY=Math.min(.895,Math.max(.105,y));if(aim!==undefined)clientAim=Math.min(55,Math.max(-55,Math.round(aim)));if(Math.abs(clientY-oldY)<.0001&&clientAim===oldAim)return;updatePlayerLabels();pendingMove={player_y:clientY,aim:clientAim};scheduleMove();}
function scheduleMove(){if(moveBusy||controlBusy||moveTimer||!pendingMove||stopped)return;moveTimer=setTimeout(flushMove,Math.max(0,33-(performance.now()-lastMoveSent)));}
async function flushMove(){moveTimer=null;if(moveBusy||controlBusy||!pendingMove||stopped)return;const cmd=pendingMove;pendingMove=null;moveBusy=true;lastMoveSent=performance.now();try{await api('/api/input',cmd);}catch(e){notice(`操作暂未完成：${e.message}`);}finally{moveBusy=false;if(commands.length)pump();else scheduleMove();}}
async function pump(){if(controlBusy||moveBusy||stopped)return;controlBusy=true;try{while(commands.length){const cmd={...(pendingMove||{}),...commands.shift()};pendingMove=null;const sync=!!(cmd.reset||cmd.mode||cmd.opponent||cmd.difficulty);try{accept(await api('/api/control',cmd),sync);}catch(e){notice(`操作暂未完成：${e.message}`);}}}finally{controlBusy=false;scheduleMove();}}
function makeBackdrop(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#101a15';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#25372e';ctx.lineWidth=1;ctx.beginPath();for(let x=35;x<w;x+=46){ctx.moveTo(x,0);ctx.lineTo(x,h);}for(let y=20;y<h;y+=46){ctx.moveTo(0,y);ctx.lineTo(w,y);}ctx.stroke();ctx.setLineDash([6,12]);ctx.strokeStyle='#415946';ctx.beginPath();ctx.moveTo(w/2,18);ctx.lineTo(w/2,h-18);ctx.stroke();return c;}
function drawCourt(now){if(!current)return;const c=$('court'),ctx=c.getContext('2d'),w=c.width,h=c.height,g=current.game;let ball=current.paused?g.ball:PongMotion.projectBall(viewGame||g,(now-viewAt)/1000);if(g.waiting_serve&&g.opponent==='human')ball={...ball,y:clientY};if(!backdrop)backdrop=makeBackdrop(w,h);ctx.drawImage(backdrop,0,0);
ctx.font='bold 16px Microsoft YaHei';ctx.fillStyle='#b7fa8e';ctx.fillText('左侧 · '+names[current.mode],24,30);ctx.textAlign='right';ctx.fillStyle='#91c9ff';ctx.fillText(g.opponent==='human'?'右侧 · 你':'右侧 · 自动反弹墙',w-24,30);ctx.textAlign='left';
trail.forEach((p,i)=>{ctx.fillStyle=`rgba(238,225,161,${i/trail.length*.2})`;ctx.beginPath();ctx.arc(p.x*w,p.y*h,3+i/trail.length*3,0,Math.PI*2);ctx.fill();});ctx.shadowBlur=12;ctx.shadowColor='#a7ef8b';ctx.fillStyle=current.mode==='rewired'?'#f3c377':'#b7fa8e';ctx.fillRect(.055*w-6,g.paddle*h-g.paddle_half*h,12,2*g.paddle_half*h);ctx.shadowBlur=0;
if(g.opponent==='human'){ctx.fillStyle='#91c9ff';ctx.fillRect(.945*w-6,clientY*h-g.right_half*h,12,2*g.right_half*h);const angle=clientAim*Math.PI/180;ctx.strokeStyle='#91c9ff';ctx.beginPath();ctx.moveTo(.925*w,clientY*h);ctx.lineTo(.925*w-Math.cos(angle)*135,clientY*h+Math.sin(angle)*95);ctx.stroke();}else{ctx.strokeStyle='#8fa98a';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(w-8,45);ctx.lineTo(w-8,h-12);ctx.stroke();}
ctx.shadowBlur=9;ctx.shadowColor='#ffe8a6';ctx.fillStyle='#f7e8b8';ctx.beginPath();ctx.arc(ball.x*w,ball.y*h,8,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(current.paused||g.waiting_serve){ctx.fillStyle='rgba(8,19,12,.45)';ctx.fillRect(w*.23,h*.38,w*.54,h*.24);ctx.fillStyle='#e5f2df';ctx.textAlign='center';ctx.font='24px Microsoft YaHei';ctx.fillText(current.paused?'已暂停':'选好回球方向，点击发球',w/2,h*.49);ctx.font='13px Microsoft YaHei';ctx.fillStyle='#a7c6b3';ctx.fillText(current.paused?'点击继续，恢复这一局':'你控制右侧蓝色球拍，左侧自动接球',w/2,h*.56);ctx.textAlign='left';}}
function animate(now){animation=null;if(stopped||document.hidden)return;drawCourt(now);frameCount++;if(now-frameAt>=1000){fps=frameCount*1000/(now-frameAt);frameAt=now;frameCount=0;$('latency-note').textContent=`${SHARED?'外网分享':'本机直连'} · 操作往返 ${networkRtt.toFixed(0)} ms · 画面 ${fps.toFixed(0)} 帧/秒`+(networkRtt>200?' · 网络延迟较高；在分享者电脑上请使用本机入口。':' · 右侧球拍即时跟手');}animation=requestAnimationFrame(animate);}
function drawActivity(){if(!current)return;const c=$('activity'),ctx=c.getContext('2d'),cw=c.width/16,ch=c.height/12;ctx.clearRect(0,0,c.width,c.height);current.features.forEach((v,i)=>{const a=Math.min(1,Math.abs(v)/.12);ctx.fillStyle=v>=0?`rgb(${32+a*140},${48+a*198},${37+a*114})`:`rgb(${32+a*107},${48+a*130},${37+a*201})`;ctx.fillRect(i%16*cw+2,Math.floor(i/16)*ch+2,cw-4,ch-4);});}
function renderBenchmarks(){if(!meta||!current)return;const key=current.mode+current.game.difficulty;if(key===benchKey)return;benchKey=key;const table=document.createElement('table');const head=document.createElement('thead');const hr=document.createElement('tr');for(const text of ['左侧控制器','入门','进阶','挑战']){const th=document.createElement('th');th.textContent=text;hr.append(th);}head.append(hr);table.append(head);const body=document.createElement('tbody');for(const row of meta.benchmark.profiles[0].results){const tr=document.createElement('tr');if(row.mode===current.mode)tr.className='selected-control';const label=document.createElement('th');label.textContent=names[row.mode];tr.append(label);for(const profile of meta.benchmark.profiles){const cell=document.createElement('td');const result=profile.results.find(r=>r.mode===row.mode);cell.textContent=(result.mean_hit_rate*100).toFixed(1)+'%';cell.title=`三个测试种子的范围：${(result.min_hit_rate*100).toFixed(0)}–${(result.max_hit_rate*100).toFixed(0)}%`;if(profile.difficulty===current.game.difficulty)cell.className='selected-difficulty';tr.append(cell);}body.append(tr);}table.append(body);$('benchmarks').replaceChildren(table);}
function render(){if(!current)return;const g=current.game;$('hits').textContent=g.hits;$('misses').textContent=g.misses;$('rate').textContent=g.hit_rate===null?'—':(100*g.hit_rate).toFixed(0)+'%';$('rally').textContent=g.best;$('action').textContent=current.action.toFixed(2);$('action-marker').style.left=`${15+(current.action+1)*35}%`;$('game-time').textContent=`游戏时间 ${g.time.toFixed(1)} s`;$('seed').textContent=`种子 ${g.seed}`;$('latency').textContent=NEURAL.has(current.mode)?current.neural_ms.toFixed(1):'—';$('hz').textContent=current.actual_hz.toFixed(1);$('mode-label').textContent=names[current.mode];$('court-label').textContent='◂ 左侧：'+names[current.mode];$('mode').value=current.mode;$('difficulty').value=g.difficulty;$('opponent').value=g.opponent;$('mode-note').textContent=notes[current.mode]||'';$('pause').textContent=current.paused?'继续':'暂停';$('run-dot').style.background=current.paused||g.waiting_serve?'#718774':'#b7fa8e';$('serve').hidden=g.opponent!=='human';$('serve').disabled=!g.waiting_serve;$('player-controls').hidden=g.opponent!=='human';$('right-score').textContent=g.opponent==='human'?`右侧：你 · 接球 ${g.right_hits} / 漏球 ${g.right_misses}`:'右侧：自动反弹';$('duel-status').textContent=g.opponent==='human'?(g.waiting_serve?'调整位置和方向，再发球':'接住右侧回球；方向滑杆对下一次回球生效'):'自动演示，可比较左侧控制器';$('graph-label').textContent=current.mode==='rewired'?'ARTIFICIAL REWIRING':NEURAL.has(current.mode)?'REAL CONNECTOME':'NO NEURAL NETWORK';$('activity-caption').textContent=!NEURAL.has(current.mode)?'该对照直接产生动作，不运行神经网络。':current.mode==='rewired'?'人工重连图的 192 个下游节点，选择规则与果蝇组一致；不是实测神经活动。':'192 个真实下游细胞的模拟活动，色标固定 ±0.12；悬停查看 ID。';$('events').replaceChildren(...current.events.map(e=>{const li=document.createElement('li'),a=document.createElement('span'),b=document.createElement('span');a.className=e.event;a.textContent=eventNames[e.event]||e.event;b.textContent=e.time.toFixed(1)+' s';li.append(a,b);return li;}));drawActivity();renderBenchmarks();}
async function poll(){if(stopped)return;if(document.hidden){setTimeout(poll,500);return;}const started=performance.now();try{const next=await api('/api/state');if(!controlBusy)accept(next,!current);failures=0;$('connection').textContent=`● ${SHARED?'远程试玩':'本机直连'} · ${meta?.config.device==='cuda'?'GPU':'CPU'}`;}catch(e){failures++;$('connection').textContent='连接暂不可用';if(failures===2)notice(e.message);}setTimeout(poll,Math.max(10,(SHARED?80:50)-(performance.now()-started)));}
async function init(){try{meta=await api('/api/meta');$('neurons').textContent=meta.config.neurons.toLocaleString('en-US');$('edges').textContent=`${(meta.config.edges/1e6).toFixed(2)} M 条原始有向连接`;$('test-size').textContent=`每档 ${meta.benchmark.seeds.length} 个测试种子 × ${meta.benchmark.encounters_per_seed} 次独立发球`;$('share-note').hidden=!SHARED;}catch(e){notice(e.message);}poll();requestAnimationFrame(animate);}
$('pause').onclick=()=>current&&control({paused:!current.paused});$('reset').onclick=()=>control({reset:true});$('serve').onclick=()=>control({serve:true});$('mode').onchange=e=>control({mode:e.target.value});$('opponent').onchange=e=>control({opponent:e.target.value});$('difficulty').onchange=e=>control({difficulty:e.target.value});$('player-height').oninput=e=>movePlayer(Number(e.target.value)/100);$('aim').oninput=e=>movePlayer(undefined,Number(e.target.value));
function pointerMove(e){if(current?.game.opponent!=='human')return;if(e.pointerType!=='mouse'&&e.type==='pointermove'&&!e.buttons)return;const r=$('court').getBoundingClientRect();movePlayer((e.clientY-r.top)/r.height);}
$('court').onpointerdown=e=>{e.preventDefault();$('court').focus();$('court').setPointerCapture(e.pointerId);pointerMove(e);};$('court').onpointermove=pointerMove;
window.addEventListener('keydown',e=>{if(!current||current.game.opponent!=='human'||['SELECT','INPUT'].includes(document.activeElement.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key)){e.preventDefault();if(e.key===' ')control({serve:true});else if(e.key==='ArrowUp'||e.key==='ArrowDown')movePlayer(clientY+(e.key==='ArrowUp'?-.04:.04));else movePlayer(undefined,clientAim+(e.key==='ArrowLeft'?-5:5));}});
$('export').onclick=async()=>{try{const data=await api('/api/export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`flywire-pong-v2-${current.game.seed}-${current.mode}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice(`已导出 ${data.records.length} 个游戏步骤`);}catch(e){notice(e.message);}};
$('shutdown').onclick=async()=>{try{await api(SHARED?'/api/leave':'/api/shutdown',{});stopped=true;$('connection').textContent=SHARED?'已退出本局':'本地服务已停止';document.querySelectorAll('button,select,input').forEach(e=>e.disabled=true);notice(SHARED?'已退出你的游戏，刷新可重新加入。':'服务已停止。');}catch(e){notice(e.message);}};
$('activity').onmousemove=e=>{if(!meta||!current||!NEURAL.has(current.mode))return;const r=e.target.getBoundingClientRect();const col=Math.min(15,Math.max(0,Math.floor((e.clientX-r.left)/r.width*16))),row=Math.min(11,Math.max(0,Math.floor((e.clientY-r.top)/r.height*12))),i=row*16+col;const ids=meta.readout_ids_by_graph[current.graph];e.target.title=`节点 ID ${ids[i]} · 模拟活动 ${current.features[i].toFixed(5)} a.u.`;};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!stopped&&animation===null){frameAt=performance.now();frameCount=0;animation=requestAnimationFrame(animate);}});
init();
