'use strict';
const $=id=>document.getElementById(id),BASE=document.documentElement.dataset.apiBase||'';
const canvas=$('brain'),gl=canvas.getContext('webgl',{alpha:false,antialias:true});
const classLabels={central:'中枢类',optic:'视叶类',sensory:'感觉类',visual_projection:'视觉投射类',ascending:'上行类',descending:'下行类',sensory_ascending:'感觉上行类',visual_centrifugal:'视觉离心类',motor:'运动类',endocrine:'内分泌类',unknown:'未标注'};
const palette=['#b9a4ec','#8cc8bd','#e6af81','#edb7ce','#b8d383','#8ebfea','#e0cc93','#afc8e1','#cfa4b3','#c5b69c','#aaaaaa'];
let data,state,program,pos,colors,colorBuffer,angleX=.16,angleY=0,zoom=1.15,selected=-1,pointer=null,renderPending=false;
const neuralNames={fly:'真实连接图',rewired:'人工重连图',untrained:'真实图 / 随机读出',disconnected:'断开连接',silenced:'关闭输入'};
const rgb=hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);
function compile(type,source){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(shader));return shader;}
function setup(){
 if(!gl)throw Error('此浏览器未启用 WebGL，无法显示三维点云。游戏与下方类型统计仍可使用。');
 const vs=compile(gl.VERTEX_SHADER,'attribute vec3 a_pos;attribute vec4 a_color;uniform vec2 u_angle;uniform float u_aspect,u_zoom,u_dpr;varying vec4 v_color;void main(){vec3 p=a_pos;float sx=sin(u_angle.x),cx=cos(u_angle.x),sy=sin(u_angle.y),cy=cos(u_angle.y);p=vec3(p.x,p.y*cx-p.z*sx,p.y*sx+p.z*cx);p=vec3(p.x*cy+p.z*sy,p.y,-p.x*sy+p.z*cy);gl_Position=vec4(p.x*u_zoom/u_aspect,p.y*u_zoom,p.z*.2,1.);gl_PointSize=(a_color.a>.9?3.4:2.0)*u_dpr;v_color=a_color;}');
 const fs=compile(gl.FRAGMENT_SHADER,'precision mediump float;varying vec4 v_color;void main(){vec2 p=gl_PointCoord-.5;if(dot(p,p)>.25)discard;gl_FragColor=v_color;}');
 program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
 const xyz=data.points.map(p=>[p[1],-p[2],p[3]]),lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];
 xyz.forEach(p=>p.forEach((v,k)=>{lo[k]=Math.min(lo[k],v);hi[k]=Math.max(hi[k],v);}));const center=lo.map((v,k)=>(v+hi[k])/2),scale=Math.max(...hi.map((v,k)=>v-lo[k]))/2;
 pos=new Float32Array(xyz.flatMap(p=>p.map((v,k)=>(v-center[k])/scale)));colors=new Float32Array(data.points.length*4);
 const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,pos,gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'a_pos');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);
 colorBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,colorBuffer);const c=gl.getAttribLocation(program,'a_color');gl.enableVertexAttribArray(c);gl.vertexAttribPointer(c,4,gl.FLOAT,false,0,0);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(.051,.086,.067,1);
 new ResizeObserver(()=>schedule()).observe(canvas);updateColors();
}
function activityColor(v){const t=Math.max(0,Math.min(1,(Math.log10(Math.max(v,1e-6))+6)/6));return [.19+.79*t,.28+.58*Math.sin(t*Math.PI/2),.25+.3*(1-Math.abs(2*t-1)),.36+.63*t];}
function updateColors(){if(!data||!gl||!colors)return;const mode=$('color-mode').value;data.points.forEach((p,i)=>{let c;if(mode==='activity')c=activityColor(state?.activity[i]||0);else if(mode==='class')c=[...rgb(palette[p[4]%palette.length]),.7];else{const flags=p[6],outFlag=state?.graph==='rewired'?4:2;c=flags&1?[...rgb('#f4c977'),.99]:flags&outFlag?[...rgb('#9ddcf4'),.99]:[.22,.3,.25,.3];}if(i===selected)c=[1,1,1,1];colors.set(c,i*4);});gl.bindBuffer(gl.ARRAY_BUFFER,colorBuffer);gl.bufferData(gl.ARRAY_BUFFER,colors,gl.DYNAMIC_DRAW);renderLegend();schedule();showSelection();}
function renderLegend(){const mode=$('color-mode').value;const labels=mode==='class'?data.class_names.map((n,i)=>[classLabels[n]||n,palette[i%palette.length]]):mode==='ports'?[['314 个输入胞体','#f4c977'],['当前网络有坐标的读出胞体','#9ddcf4'],['其余抽样胞体','#486b50']]:[['|x| ≤ 10⁻⁶','#354d42'],['10⁻³','#96ad73'],['1','#fae083'],['固定对数色标 / a.u.（非 Hz）',null]];$('legend').replaceChildren(...labels.map(([text,color])=>{const span=document.createElement('span');if(color){const dot=document.createElement('i');dot.style.background=color;span.append(dot);}span.append(document.createTextNode(text));return span;}));}
function schedule(){if(renderPending)return;renderPending=true;requestAnimationFrame(()=>{renderPending=false;draw();});}
function draw(){if(!program)return;const dpr=Math.min(window.devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.clear(gl.COLOR_BUFFER_BIT);gl.uniform2f(gl.getUniformLocation(program,'u_angle'),angleX,angleY);gl.uniform1f(gl.getUniformLocation(program,'u_aspect'),w/h);gl.uniform1f(gl.getUniformLocation(program,'u_zoom'),zoom);gl.uniform1f(gl.getUniformLocation(program,'u_dpr'),dpr);gl.drawArrays(gl.POINTS,0,data.points.length);}
function pick(e){if(!pos)return;const r=canvas.getBoundingClientRect(),cx=e.clientX-r.left,cy=e.clientY-r.top;let best=12*12,found=-1;const sx=Math.sin(angleX),ax=Math.cos(angleX),sy=Math.sin(angleY),ay=Math.cos(angleY);for(let i=0;i<data.points.length;i++){const x=pos[3*i],y=pos[3*i+1]*ax-pos[3*i+2]*sx,z=pos[3*i+1]*sx+pos[3*i+2]*ax,rx=x*ay+z*sy,px=r.width/2+rx*zoom*r.height/2,py=r.height/2-y*zoom*r.height/2,dist=(px-cx)**2+(py-cy)**2;if(dist<best){best=dist;found=i;}}selected=found;updateColors();}
function showSelection(){if(selected<0)return;const p=data.points[selected];$('selection').textContent=`ID ${p[0]} · ${p[5]} · ${classLabels[data.class_names[p[4]]]||data.class_names[p[4]]} · |x| = ${(state?.activity[selected]||0).toExponential(2)} a.u. · 胞体 (${p[1]}, ${p[2]}, ${p[3]}) μm` ;}
async function poll(){if(document.hidden){setTimeout(poll,1000);return;}try{const response=await fetch(BASE+'/api/brain',{cache:'no-store'});const next=await response.json();if(!response.ok)throw Error(next.error||'连接失败');if(next.activity.length!==data.points.length)throw Error('点位与活动数量不一致，请刷新网页');state=next;$('atlas-status').textContent=!state.neural_controller?'当前对照不运行神经网络':`${neuralNames[state.mode]} · ${state.paused?'暂停，保留当前状态':state.waiting_serve?'等待游戏发球':state.actual_hz.toFixed(1)+' 次游戏更新 / 秒'}`;const informative=state.neural_controller&&state.max_abs>1e-7;$('types').replaceChildren(...(informative?state.top_types.map(t=>{const li=document.createElement('li'),name=document.createElement('span'),value=document.createElement('b'),n=document.createElement('small');name.textContent=t.name;value.textContent=t.mean_abs.toExponential(2);n.textContent=`${t.n} 个同类细胞 · 平均 |x| / a.u.`;li.append(name,value,n);return li;}):[Object.assign(document.createElement('li'),{textContent:state.neural_controller?'当前没有非零模拟活动。到游戏页发球，或使用自动演示。':'规则 / 直接状态 / 随机动作对照不计算神经活动。'})]));updateColors();}catch(e){$('atlas-status').textContent=e.message;}setTimeout(poll,1000);}
$('back').href=BASE+'/';$('color-mode').onchange=updateColors;$('rotate').oninput=e=>{angleY=Number(e.target.value)*Math.PI/180;schedule();};$('zoom').oninput=e=>{zoom=Number(e.target.value)/100;schedule();};$('reset-view').onclick=()=>{angleX=.16;angleY=0;zoom=1.15;$('rotate').value=0;$('zoom').value=115;schedule();};
canvas.onpointerdown=e=>{pointer={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!pointer)return;angleY+=(e.clientX-pointer.x)*.007;angleX+=(e.clientY-pointer.y)*.007;pointer.x=e.clientX;pointer.y=e.clientY;$('rotate').value=((angleY*180/Math.PI+180)%360+360)%360-180;schedule();};canvas.onpointerup=e=>{if(pointer&&Math.hypot(e.clientX-pointer.startX,e.clientY-pointer.startY)<5)pick(e);pointer=null;};canvas.onpointercancel=()=>{pointer=null;};canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.6,Math.min(2.6,zoom*Math.exp(-e.deltaY*.001)));$('zoom').value=zoom*100;schedule();},{passive:false});
(async()=>{try{const r=await fetch(BASE+'/brain-data.json');if(!r.ok)throw Error('无法加载位置数据');data=await r.json();const m=data.manifest;$('coverage').textContent=`模型共 ${m.model_neurons.toLocaleString()} 个节点，其中 ${m.neurons_with_soma.toLocaleString()} 个有实测胞体坐标；本图抽样显示 ${m.displayed_somas.toLocaleString()} 个，包含全部 314 个输入胞体、191 / 192 个真实图读出胞体。${m.missing_soma_not_plotted.toLocaleString()} 个节点缺少胞体坐标而未绘出，仍参与网络计算。坐标由官方 4×4×40 nm 体素转换为 μm。`;try{setup();}catch(e){$('selection').textContent=e.message;$('selection').classList.add('atlas-error');}poll();}catch(e){$('atlas-status').textContent=e.message;}})();
